version: "2"
services:
  mongo:
    build:
        context: .
        dockerfile: dockerfiles/dockerfile_mongo
    ports:
      - "27017:27017"
  reddit:
    build:
        context: .
        dockerfile: dockerfiles/dockerfile_python
    volumes:
      - .:/code
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      DATABASE_NAME: hootsuite-challenge
  web:
    build:
        context: .
        dockerfile: dockerfiles/dockerfile_flask
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      DATABASE_NAME: hootsuite-challenge
      WEB_SERVER: 0.0.0.0
      WEB_PORT: 5000