# Pull base image.
FROM mongo

# Define mountable directories.
VOLUME ["/data/db"]

# Define working directory.
WORKDIR /data

# trebuie sa
# configurez index pentru mongo db
# (cred ca nu trebuie python)


# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017
EXPOSE 28017